### ISSUE TITLE
Create simplified infrastructure for saving and retrieving matches, using a Facade

### ISSUE THREAD

**Issue by hjorthjort** [hjorthjort/CapStat#11]
Responsibilities include:

Save a new match to local "file", using Sasers file interface class.
Save from that file, using a background Thread (that should not be part of the Facade, probably).
Retrieve matches from the database (get basic info, and create new match via a Factory)

**Comment by hjorthjort** [comment]
The repositories UserLedger and MatchLedger should reconstitute stored objects by delegating to the factories. These could reasonably have package private methods specifically accepting the right kind of value objects and returning a new User object, without automatically saving them somewhere, like the standard methods might do.

**Comment by lol2kpe** [comment]
Both Users and Matches (incl. ThrowSequences) can now be inserted and fetched to/from the database
