### ISSUE TITLE
Implement a "task queue" for temporary storage of SQL queries

### ISSUE THREAD

**Issue by saser** [hjorthjort/CapStat#14]
As mentioned in #10, a possible solution for temporary storage of matches is to store SQL queries (for insertion of matches into the database) in a text file on the computer, in case a connection to the database is not available. This can be abstracted to a "task queue": a queue of tasks to perform, that can be added to and removed from, on a FIFO ("first in, first out") basis.

A solution that this issue suggests is to have a `ITaskQueue` interface and have different concrete implementations of that interface, e.g. storing SQL queries in a text file.

**Comment by hjorthjort** [comment]
Should we consider #10 to be closed now as well?
