### ISSUE TITLE
Timestamp to be inserted into database

### ISSUE THREAD

**Issue by lol2kpe** [hjorthjort/CapStat#16]
We need date/time for a match to be inserted into the database. This will preferably be the starting time of the match.

**Comment by saser** [comment]
We should also have an end time, so we have a start time and an end time.

**Comment by lol2kpe** [comment]
ATM there is an attribute in the database for "elapsed time" too. Either we leave it as it is or we change this and dateTime to startDateTime and endDateTime.

**Comment by hjorthjort** [comment]
start time and end time separately, in the same format, seems like the simpler approach.
