### ISSUE TITLE
Create value objects for matches and users in the infrastructure layer that can be returned by the facade for database queries

### ISSUE THREAD

**Issue by hjorthjort** [hjorthjort/CapStat#17]
These should be simple value objects, containing everything needed to create a user, like nickname (String), ELORanking (Double), etc, and the same for matches. 

**This is an important part of separating the infrastructure layer from the domain layer, as the infrastructure layer should have no dependence on the domain layer or the classes in it.**

Name suggestions: 
- "UserDatabaseRow" and "MatchDatabaseRow"
- "UserValueObject" and "MatchValueObject"

**Comment by hjorthjort** [comment]
This issue is actually a sub-issue to issue #11

**Comment by lol2kpe** [comment]
Implemented with UserBlueprint and MatchResultBlueprint (and PartialSequenceBlueprint).

**Comment by lol2kpe** [comment]
Implemented with UserBlueprint and MatchResultBlueprint (and PartialSequenceBlueprint).
