### ISSUE TITLE
Decide starting player from ChalmersAge, or let user choose

### ISSUE THREAD

**Issue by hjorthjort** [hjorthjort/CapStat#4]
Who starts the game should be automatically decided by the match based on the ChalmersAge of the players. However, it should also be possible for the spectator to decide starting player, regardless of the players' ages, or if the players have not been set yet. 

These two features should ideally be implemented together, since they might interfere with each other.

**Comment by saser** [comment]
This could probably be implemented fairly easily, by splitting the process in two parts:
1. Let Match supply a method that calculates the starting player
2. Let Match supply a setter that can set the current player

With this distinction, we can have e.g. the GUI automatically use both methods to set the starting player in the beginning of a match. If the spectator manually chooses the current player, only the second method needs to be used.
