### ISSUE TITLE
Specify and implement equals() for classes

### ISSUE THREAD

**Issue by saser** [hjorthjort/CapStat#8]
There should be good specifications and implementations for equals() for more or less all classes that we have created. Both because it makes sense, and because it will probably help us in our unit testing later (I'm guessing JUnit's assertEquals() uses equals() to check for equality).

**Comment by saser** [comment]
Just realized that at the time of this writing, all classes that make sense to have an `equals()` implementation for already has one (see #4). I'll keep myself assigned to this issue as an ongoing effort to implement `equals()` for new classes, as the need arises.

**Comment by hjorthjort** [comment]
Has been done organically where needed. Closing.
